### PR TITLE
CAF-1393: Updated with license header

### PR DESCRIPTION
**Pull request by arogan92**
Updated all .java, .xml and .sh files to include Apache license disclaimer.

Could I get a code review just to check that the license is correct and that there are no other file types that should be included?

### CODE REVIEW

**Comment by glucy** [comment]
At a very quick glance you have covered off most files:
~/code/worker-framework
[lucyg.LUCYG1] ➤ find . -name "*.java" | wc -l
241
[lucyg.LUCYG1] ➤ find . -name "*.xml" | wc -l
28
[lucyg.LUCYG1] ➤ find . -name "*.sh" | wc -l
2
[lucyg.LUCYG1] ➤ find . -name "*.Codec" | wc -l
0
[lucyg.LUCYG1] ➤ find . -name "*.yaml" | wc -l
2
[lucyg.LUCYG1] ➤ find . -name "*.html" | wc -l
384

Total: 657

You've changed 666 files

**Comment by dermot-hardy** [comment]
Same issue with .sh file headers

**Comment by arogan92** [comment]
Fixed some spacing in .sh file

**Comment by dermot-hardy** [comment]
You've changed 666 files - what could go wrong?

**Comment by arogan92** [comment]
If you say my name 3 times in front of a mirror Worker-Framework will break!

**Pull request merged**
