### PR TITLE
SCMOD-5090: Develop Build issue fix

### PR DESCRIPTION
**Pull request by thilagasanthosh**
https://autjira.microfocus.com/browse/SCMOD-5090

### CODE REVIEW

**Comment by michael-bryson** [comment]
I'm not sure about this one with regards to the versions in the pom of the archetype testing project. @dermot-hardy can you have a look at this please?

**Comment by thilagasanthosh** [comment]
@michael-bryson ,
There was build issue in local while removing the version numbers.


[ERROR]   The project com.hpe.caf.it.worker:worker-example-testing:1.0.0-SNAPSHOT (C:\Users\santhoth\source\WorkerFramework\worker-framework\worker-archetype\target\test-classes\projects\basic\project\worker-example\worker-example-testing\pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for com.github.workerframework:worker-testing-integration:jar is missing. @ line 40, column 21
[ERROR]     'dependencies.dependency.version' for org.testng:testng:jar is missing. @ line 44, column 21

So added the version back.

**Comment by thilagasanthosh** [comment]
http://sou-jenkins2.hpeswlab.net/job/WorkerFramework/view/Developer/job/WorkerFramework~worker-framework~SCMOD-5090~CI/

**Review by dermot-hardy — APPROVED** [review]
The archetype does need work, but raise a separate Jira for it.  What's done now is sufficient for this Jira.

**Comment by thilagasanthosh** [comment]
New Jira created for removing version numbers from archetype pom files.

https://autjira.microfocus.com/browse/SCMOD-5719

**Pull request merged**
